### ISSUE TITLE
哇，居然又支持了

### ISSUE THREAD

**Issue by handashuai** [tencentyun/qcloud-sdk-dotnet#1]
newtonsjson 能不能放 nuget 引用 这个 包太jiba 大了

**Comment by bradyxiao** [comment]
1， cos xml C# sdk 依赖于 Newtonsoft,json;
2, Newtonsoft,json 可以直接通过 nuget 来引用;
3，cos xml 目前也只 支持 nuget 引用，搜索 Tencent.QCloud.Cos.Sdk
