### ISSUE TITLE
SDK不支持下载文件到内存.....

### ISSUE THREAD

**Issue by fishjimi** [tencentyun/qcloud-sdk-dotnet#18]
为了性能考虑，我所有代码对文件的操作都是在内存里完成的。
结果到了COS这里居然只能下载到本地，哭了

**Comment by konakonall** [comment]
@fishjimi 支持下载到内存，请参考 https://github.com/tencentyun/qcloud-sdk-dotnet/blob/9c17ef2033ceb5366d9bf0818f8b44978ff12774/QCloudCSharpSDK/COSXMLTests/ObjectTest.cs#L701

**Comment by fishjimi** [comment]
噢！我就说怎么会没有，文档没找到，感谢！
