### ISSUE TITLE
SDK从5.4.19升级到5.4.20后报403错误，回退后又正常

### ISSUE THREAD

**Issue by fairok** [tencentyun/qcloud-sdk-dotnet#20]
在5.4.19中正常，升级到5.4.20报如下错误，回退到5.4.19又正常。
COSXML.CosException.CosServerException: CosServerException: 403 - Forbidden at COSXML.Network.HttpClient.CosResponse.PaserServerError(Stream inputStream, String contentType, Int64 contentLength) at COSXML.Network.ResponseBody.HandleResponseBody(Stream inputStream) at COSXML.Network.CommandTask.HandleHttpWebResponse(HttpWebResponse httpWebResponse, Response response) at COSXML.Network.CommandTask.Excute(Request request, Response response, HttpClientConfig config) at COSXML.Network.HttpClient.InternalExcute(CosRequest cosRequest, CosResult cosResult, QCloudCredentialProvider credentialProvider) at COSXML.Network.HttpClient.Excute(CosRequest cosRequest, CosResult cosResult, QCloudCredentialProvider credentialProvider) at COSXML.CosXmlServer.Excute(CosRequest request, CosResult result) at COSXML.CosXmlServe

**Comment by brischan** [comment]
后续版本已修复，试下5.4.21及以上版本～
