### ISSUE TITLE
.Net Core环境下的bug

### ISSUE THREAD

**Issue by visionding** [tencentyun/qcloud-sdk-dotnet#3]
[https://github.com/tencentyun/qcloud-sdk-dotnet/blob/4cb213d1088dacdb3903aa90fba7945a5557c8f0/QCloudCSharpSDK/COSXML/Network/CommandTask.cs#L494](https://github.com/tencentyun/qcloud-sdk-dotnet/blob/4cb213d1088dacdb3903aa90fba7945a5557c8f0/QCloudCSharpSDK/COSXML/Network/CommandTask.cs#L494)

在.Net Core环境下这里有问题，运行在Linux系统下的时候isMonoPlatform返回true，但是.Net Core中WebHeaderCollection的方法是AddWithoutValidate，会抛出空引用异常

**Comment by bradyxiao** [comment]
已fix
