### ISSUE TITLE
当本地时间执行夏令时的时候，TimeUtils.GetCurrentTime()返回的时间与正确值相差1小时

### ISSUE THREAD

**Issue by taojianzzh** [tencentyun/qcloud-sdk-dotnet#5]
比如：把当前机器时间设置为美国东部时间UTC-5，当前正在使用夏令时。
当前代码的计算方法很可能是错误的。https://github.com/tencentyun/qcloud-sdk-dotnet/blob/master/QCloudCSharpSDK/COSXML/Utils/TimeUtils.cs#L17
实际值和正确值相差3600秒。
这将导致签名中的时间都是不正确，和腾讯服务器时间不一致。
测试结果：GenerateSignURL产生的url无法打开资源，服务器返回
`<Code>AccessDenied</Code><Message>Request has expired</Message>`

**Comment by bradyxiao** [comment]
thanks
copy from  https://github.com/tencentyun/qcloud-sdk-dotnet/blob/54870ccdfa9aa92613097a068036517053728d3b/QCloudCSharpSDK/COSXML/Utils/TimeUtils.cs
