### ISSUE TITLE
官方sdk 中 GetObjetc 能否支持 Stream输出 

### ISSUE THREAD

**Issue by sitsh** [tencentyun/qcloud-sdk-dotnet#8]
我们从 阿里cos 迁移过来 发现 读取一个对象 腾讯sdk 只能保存成文件 不够灵活 多数情况下 是需要读取成 流后 ，输出处理。 阿里sdk有对应的 方法，但是腾讯 就提供了 保存本地文件的方法。
自己修改源码 可以简单实现  但是 已经就不能同步更新 官方sdk了。请求官方加入此功能

**Comment by bradyxiao** [comment]
已添加了一个方法 
 GetObjectBytesResult GetObject(GetObjectBytesRequest request);

        void GetObject(GetObjectBytesRequest request, COSXML.Callback.OnSuccessCallback<CosResult> successCallback, COSXML.Callback.OnFailedCallback failCallback);

**Comment by FatTigerWang** [comment]
能否将此方法支持发布到nuget?

**Comment by sitsh** [comment]
> 能否将此方法支持发布到nuget?

自己下载源码编译下 上传nuget 就好了..

不想编译 你也可以先用我之前自己修改的版本  因为就修改添加了 一个方法我懒得重新编译 官方版本重新上传了。。
https://www.nuget.org/packages/COSXML.Wpre/
以后等官方 发布 在替换回来
