### ISSUE TITLE
为什么不用net standard的库而要依赖netcoreapp???

### ISSUE THREAD

**Issue by FatTigerWang** [tencentyun/qcloud-sdk-dotnet#9]
为什么不用net standard的库而要依赖netcoreapp???

**Comment by FatTigerWang** [comment]
nuget包能否将Net Framework和NetCoreApp的依赖去除. 用Net Standard的nuget包替换

**Comment by cuibty** [comment]
确实很诡异

**Comment by FatTigerWang** [comment]
> 确实很诡异

根本没搞清楚这三个库的定位就瞎写，作为大厂要起到引领标准的带头作用而不是瞎玩.

**Comment by konakonall** [comment]
已改成依赖 . NET standard.

**Comment by cuibty** [comment]
Tencent.QCloud.Cos.Sdk
Tencent.QCloud.Cos.Sdk.NetCore

这两个包，有区别吗？@konakonall

**Comment by konakonall** [comment]
@cuibty 用 Tencent.QCloud.Cos.Sdk 的 5.4.5版本就可以

**Comment by FatTigerWang** [comment]
@konakonall :+1:
